#ifndef RENSA_FFI_H
#define RENSA_FFI_H

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct RensaRMinHashCtx RensaRMinHashCtx;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

uint32_t rensa_ffi_abi_version(void);

/**
 * Free a context created by [`rensa_rminhash_ctx_new`].
 *
 * # Safety
 *
 * `ctx` must be either null, or a pointer returned by
 * [`rensa_rminhash_ctx_new`]. It must be freed at most once, and must not be
 * used after being freed.
 */
void rensa_rminhash_ctx_free(RensaRMinHashCtx *ctx);

RensaRMinHashCtx *rensa_rminhash_ctx_new(size_t num_perm, uint64_t seed);

/**
 * Compute an R-MinHash digest from pre-hashed tokens (`u64` feature hashes).
 *
 * The digest is written into `out_digest` (a `u32` array). The output buffer
 * length must match the context's `num_perm`.
 *
 * Returns 0 on success, or a small error code:
 * - 1: null pointer
 * - 2: output length mismatch
 * - 3: invalid live context or internal failure
 *
 * # Safety
 *
 * - `ctx` must be either null, or a pointer returned by
 *   [`rensa_rminhash_ctx_new`] that has not been freed.
 * - Passing a freed, foreign, or otherwise invalid pointer is undefined
 *   behavior. The defensive magic-tag check only applies to still-live memory.
 * - `out_digest` must be either null (in which case an error is returned), or
 *   a pointer to a writable buffer of `out_digest_len` `u32` values.
 * - If `token_hashes_len != 0`, `token_hashes` must be a pointer to a readable
 *   buffer of `token_hashes_len` `u64` values.
 */
int32_t rensa_rminhash_digest_prehashed(const RensaRMinHashCtx *ctx,
                                        const uint64_t *token_hashes,
                                        size_t token_hashes_len,
                                        uint32_t *out_digest,
                                        size_t out_digest_len);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* RENSA_FFI_H */
